In [28]:
#Importamos las herramientas a utilizar
import numpy as np
import random
#Creamos una función que recibira la matriz de distancias y un numero de iteraciones asi como una distancia sobre la cual probar 
def tsp_aleatorio(matriz_distancias,n):
    #Asignamos un número del 1 al tamaño de un renglón de la matriz a cada lugar y lo guardamos en una lista de lugares
    matriz_mejores_permutaciones=[]
    lugares = range(1, matriz_distancias.shape[0]-1)
    #Inicializamos la mejor permutación como una aleatoria de los lugares
    mejor_permutacion =np.concatenate((np.array([0]),np.random.permutation(lugares)))
    #mejor_permutacion=np.insert(mejor_permutacion,0,0)
    #Inicializamos el mejor costo en la distancia proveida o bien en infinito
    mejor_costo=costo_permutacion(mejor_permutacion,matriz_distancias)
    i=0
    
    #Iteramos el problema n veces
    while (i<n):
        permutacion=mejor_permutacion
        #Encontramos una permutación en el vecindario de la guardada
        ix1=random.randint(1, len(permutacion)-1);ix2=random.randint(1, len(permutacion)-1)
        temp=permutacion[ix1]
        permutacion[ix1]=permutacion[ix2]
        permutacion[ix2]=temp
        #Encontramos el costo de dicha permutación
        costo=costo_permutacion(permutacion,matriz_distancias)
        #Guardamos el costo y la permutación si estos son mejores que los datos anteriormente guardados
        if (costo <mejor_costo):
            mejor_permutacion = permutacion
            print(mejor_permutacion)
            mejor_costo=costo
            print(costo)
            matriz_mejores_permutaciones.append((mejor_permutacion,mejor_costo))

        i+=1
    #Regresamos la solución en una tupla    

def costo_permutacion(permutacion,matriz_distancias):
    L=[]
    #Guardamos en una lista los costos de los trayectos
    for i in range(len(permutacion)-1):
        L.append(matriz_distancias[permutacion[i]][permutacion[i+1]])
    #Sumamos los costos de los trayectos junto con el de regresar  
    return sum(L)+matriz_distancias[permutacion[-1]][permutacion[0]]

caso=([
  [9999, 3, 5, 48, 48, 8, 8, 5, 5, 3, 3, 0, 3, 5, 8, 8, 5],
  [3, 9999, 3, 48, 48, 8, 8, 5, 5, 0, 0, 3, 0, 3, 8, 8, 5],
  [5, 3, 9999, 72, 72, 48, 48, 24, 24, 3, 3, 5, 3, 0, 48, 48, 24],
  [48, 48, 74, 9999, 0, 6, 6, 12, 12, 48, 48, 48, 48, 74, 6, 6, 12],
  [48, 48, 74, 0, 9999, 6, 6, 12, 12, 48, 48, 48, 48, 74, 6, 6, 12],
  [8, 8, 50, 6, 6, 9999, 0, 8, 8, 8, 8, 8, 8, 50, 0, 0, 8],
  [8, 8, 50, 6, 6, 0, 9999, 8, 8, 8, 8, 8, 8, 50, 0, 0, 8],
  [5, 5, 26, 12, 12, 8, 8, 9999, 0, 5, 5, 5, 5, 26, 8, 8, 0],
  [5, 5, 26, 12, 12, 8, 8, 0, 9999, 5, 5, 5, 5, 26, 8, 8, 0],
  [3, 0, 3, 48, 48, 8, 8, 5, 5, 9999, 0, 3, 0, 3, 8, 8, 5],
  [3, 0, 3, 48, 48, 8, 8, 5, 5, 0, 9999, 3, 0, 3, 8, 8, 5],
  [0, 3, 5, 48, 48, 8, 8, 5, 5, 3, 3, 9999, 3, 5, 8, 8, 5],
  [3, 0, 3, 48, 48, 8, 8, 5, 5, 0, 0, 3, 9999, 3, 8, 8, 5],
  [5, 3, 0, 72, 72, 48, 48, 24, 24, 3, 3, 5, 3, 9999, 48, 48, 24],
  [8, 8, 50, 6, 6, 0, 0, 8, 8, 8, 8, 8, 8, 50, 9999, 0, 8],
  [8, 8, 50, 6, 6, 0, 0, 8, 8, 8, 8, 8, 8, 50, 0, 9999, 8],
  [5, 5, 26, 12, 12, 8, 8, 0, 0, 5, 5, 5, 5, 26, 8, 8, 9999]],
 39)

h=tsp_aleatorio(np.array(caso[0]),10000000)


[ 0  3  4 13 10  8 11 15  5  6 12 14  7  2  9  1]
199
[ 0  3  4 14 10  8 11 15  5  6 12 13  7  2  9  1]
147
[ 0 14 15 12  2 13 11 10  8  9  1  6  5  7  4  3]
113
[ 0  7 15 11  9  5  1 10  2 13  8  4  3 14  6 12]
96
[ 0  5 15 12  1  3  4 14  6  8  7 11 10  9  2 13]
94
[ 0 10  5 12 11  6 14  8  7  3  4 15  1  2  9 13]
78
[ 0 10  1 14  7  9 13  2 11 12  8 15  4  3  6  5]
68
[ 0 13  2 10  8 12  9  7  1 15  3  4  5 14  6 11]
56
[ 0  1  7  8 11 13  2 10 12  5 15  3  4  6 14  9]
52
[ 0  2  1 11 12 13 10  9  8  7  3  4  5 15  6 14]
51
[ 0 13  2 10  9  8  7  6  5  4  3 14 15  1 12 11]
44
[ 0 11  2 13  9 12 10  1  5 15  6 14  3  4  7  8]
39


In [30]:
costo_permutacion([ 0 ,11 , 2 ,13 , 9 ,12 ,10 , 1 , 5 ,15 , 6 ,14 , 3  ,4 , 7 , 8],caso[0])

39